<font color='red'><b>**WARNING**</b></font> <br/>
어떠한 사유로도 임의로 복사, 촬영, 녹음, 복제, 보관, 전송하거나 허가 받지 않은 저장매체를 이용한 보관, 제3자에게 누설, 공개 또는 사용하는 등의 무단 사용 및 불법 배포 시 법적 조치를 받을 수 있습니다. <br/>

<div style="text-align: right; color: #7f8c8d; font-size: 0.9em; margin-top: 20px;">
📝 Author: 박사홍 (Sahong Pak)</br>
📧 Contact: sahong.pak@gmail.com</br>
📌 Version: v2.0</br>
📅 Last Updated: 2026-03-12</br>
</div>

</br>

# 학습 내용
>이번 장에서는 <strong>NumPy 기초(NumPy Fundamentals)</strong>에 대해 학습합니다.</br></br>
>다차원 배열(ndarray)의 생성, 인덱싱, 연산, 브로드캐스팅을 학습해봅시다.

</br>

In [ ]:
# TODO 0: 실습을 위해 numpy 모듈을 추가하고 별칭을 np로 설정해봅시다.
import numpy as np



</br>

# NumPy 배열 (ndarray)
> NumPy는 <mark style="background-color:#FFF9C4; padding:2px 6px; border-radius:4px;">고성능 다차원 배열(ndarray)</mark>을 제공하는 수치 연산 라이브러리입니다.</br>
> Python 리스트보다 메모리 효율적이고 연산 속도가 빠릅니다.

>Python 리스트로 백만 개의 숫자를 2배로 만들려면 `for` 반복문이 필요합니다. 느립니다.</br>
>NumPy는 같은 작업을 `arr * 2` 한 줄로, <mark style="background-color:#FFF9C4; padding:2px 6px; border-radius:4px;">내부적으로 C 언어 수준의 속도</mark>로 처리합니다.</br>
>실제 벤치마크에서 NumPy는 Python 리스트보다 <mark style="background-color:#FFF9C4; padding:2px 6px; border-radius:4px;">수십 배에서 100배 이상 빠릅니다</mark>.</br>
>메모리 측면에서도 Python 리스트는 각 숫자를 객체로 저장하지만, NumPy 배열은 연속된 메모리 블록에 순수 숫자만 저장하여 훨씬 적은 메모리를 사용합니다.

><mark style="background-color:#FFF9C4; padding:2px 6px; border-radius:4px;">벡터화</mark>란 반복문 없이 배열 전체에 한 번에 연산을 적용하는 방식입니다.</br>
머신러닝에서 가중치 업데이트, 데이터 정규화, 행렬 곱셈 등의 연산은 수백만 번 반복되는데, Python `for` 루프로는 이런 연산이 실용적인 시간 안에 끝나지 않습니다.</br>
>NumPy의 벡터화 연산은 Pandas, TensorFlow, scikit-learn 등 <mark style="background-color:#FFF9C4; padding:2px 6px; border-radius:4px;">데이터 과학 생태계 전체의 기반</mark>이며, NumPy를 이해하면 이 도구들의 동작 방식을 훨씬 깊이 이해할 수 있습니다.

In [4]:
# TODO 1: array에 [1, 2, 3, 4, 5]를, matrix에 [[1, 2, 3], [4, 5, 6]]을 NumPy 배열로 저장하고, 각 배열과 shape를 출력해봅시다.

array = np.array([1, 2, 3, 4, 5]) # 넘파이로 배열 생성
matrix = np.array([[1, 2, 3], [4, 5, 6]]) # 넘파이로 행렬 생성

print("Array:", array) # 배열 출력
print("Array shape:", matrix) # 배열의 shape 출력

print(array.shape)
print(matrix.shape)

Array: [1 2 3 4 5]
Array shape: [[1 2 3]
 [4 5 6]]
(5,)
(2, 3)


</br>

## 배열 속성

<table style="width:100%">
  <thead>
    <tr>
      <th style="text-align:center">속성</th>
      <th>설명</th>
      <th>예시</th>
    </tr>
  </thead>
  <tbody>
    <tr><td style="text-align:center"><code>shape</code></td><td>차원별 크기</td><td><code>(2, 3)</code></td></tr>
    <tr><td style="text-align:center"><code>ndim</code></td><td>차원 수</td><td><code>2</code></td></tr>
    <tr><td style="text-align:center"><code>dtype</code></td><td>데이터 타입</td><td><code>float64</code></td></tr>
    <tr><td style="text-align:center"><code>size</code></td><td>전체 요소 수</td><td><code>6</code></td></tr>
  </tbody>
</table>

</br>

## 배열 생성 함수

<table style="width:100%">
  <thead>
    <tr>
      <th style="text-align:center">함수</th>
      <th>설명</th>
    </tr>
  </thead>
  <tbody>
    <tr><td style="text-align:center"><code>np.zeros(shape)</code></td><td>모든 원소가 0인 배열 생성</td></tr>
    <tr><td style="text-align:center"><code>np.arange(start, stop, step)</code></td><td>시작~끝(미포함)까지 step 간격의 배열 생성</td></tr>
    <tr><td style="text-align:center"><code>np.linspace(start, stop, num)</code></td><td>시작~끝(포함)을 num개로 균등 분할한 배열 생성</td></tr>
    <tr><td style="text-align:center"><code>np.ones(shape)</code></td><td>모든 원소가 1인 배열 생성</td></tr>
    <tr><td style="text-align:center"><code>np.full(shape, val)</code></td><td>특정 값으로 채운 배열 생성</td></tr>
    <tr><td style="text-align:center"><code>np.eye(n)</code></td><td>n×n 단위행렬(대각선이 1) 생성</td></tr>
    <tr><td style="text-align:center"><code>np.random.randint(low, high, size)</code></td><td>범위 내 랜덤 정수 배열 생성</td></tr>
    <tr><td style="text-align:center"><code>np.random.randn(d0, d1, ...)</code></td><td>표준정규분포 난수 배열 생성</td></tr>
  </tbody>
</table>

In [ ]:
# TODO 2: 모든 원소가 0인 2x3 행렬, 0부터 10까지 2간격 행렬, 0부터 1사이를 5개로 균등하게 나눈 행렬을 출력해봅시다.

print(np.zeros((2,3)))

print(np.arange(0, 10, 2))

print(np.linspace(0, 1, 5))

[[0. 0. 0.]
 [0. 0. 0.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


In [ ]:
# TODO 3: 2x3 크기에 1로 채운 행렬, 2x3에 7을 채운 행렬, 3x3 크기의 단위행렬, 2x3 크기의 0-9 범위 랜덤 정수 행렬, 2x3 크기의 정규분포 난수 행렬을 출력해봅시다.

# 2x3 크기에 1로 채운 행렬
print(np.ones((2,3)))

# 2x3에 7을 채운 행렬
print(np.full((2,3), 7))

# 3x3 크기의 단위행렬
print(np.eye(3))

# 2x3 크기의 0-9 범위 랜덤 정수 행렬
print(np.random.randint(0,10, (2,3)))

# 2x3 크기의 정규분포 난수 행렬
print(np.random.randn(2,3))

[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7 7]
 [7 7 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[2 6 7]
 [2 5 7]]
[[ 0.90149132 -0.87710695  0.53704924]
 [ 0.17031308 -0.35643768  1.12118533]]


</br>

## 인덱싱과 슬라이싱 (Indexing & Slicing)

In [25]:
# TODO 4: 1부터 9까지 3x3 크기의 행렬을 matrix에 저장하고,
#         - 0행 1열
#         - 1행 전체
#         - 2열 전체
#         - 0-1행, 1-2열 2x2 크기의 부분행렬
#         을 출력해봅시다.


matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

# 0행 1열
print(matrix[0][1])

# 1행 전체
print(matrix[1])

# 2열 전체
print(matrix[2])

# 0-1행, 1-2열 2x2 크기의 부분행렬
print(matrix[0:2, 1:3])

2
[4 5 6]
[7 8 9]
[[2 3]
 [5 6]]


</br>

### 불리언 인덱싱 (Boolean Indexing)

In [28]:
# TODO 5: 10, 25, 30, 45, 50 데이터를 1x5 크기의 행렬을 array에 저장하고, 30을 초과하는 조건을 생성하여 필터링된 결과를 출력해봅시다.
matrix = np.array([10, 25, 30, 45, 50])

mask = matrix > 30

print(mask)
print(matrix[mask])

[False False False  True  True]
[45 50]


</br>

## reshape과 차원 변환
> `reshape`은 <mark style="background-color:#FFF9C4; padding:2px 6px; border-radius:4px;">데이터를 유지하면서 배열의 형태를 변경</mark>합니다.

In [35]:
# TODO 6: arange를 이용하여 0부터 11을 array에 저장하고, 3x4 크기로 변환하여 matrix에 저장 후 결과를 출력해봅시다.
array = np.arange(12)

print("Array:", array)

# 차원을 3x4로 변환 하고 싶다.
matrix = array.reshape((3,4))
print("Matrix:\n", matrix)

Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Matrix:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


💡reshape 주의
> 변환 전후의 전체 요소 수가 같아야 합니다.</br>
> `-1`을 사용하면 해당 차원의 크기를 자동 계산합니다.

</br>

## 배열 변환 (Array Transformation)

<table style="width:100%">
  <thead>
    <tr>
      <th style="text-align:center">함수</th>
      <th>설명</th>
    </tr>
  </thead>
  <tbody>
    <tr><td style="text-align:center"><code>arr.flatten()</code></td><td>다차원 배열을 1차원으로 변환</td></tr>
    <tr><td style="text-align:center"><code>arr.T</code> / <code>np.transpose(arr)</code></td><td>행과 열을 전치(transpose)</td></tr>
    <tr><td style="text-align:center"><code>np.tile(arr, reps)</code></td><td>배열을 지정한 횟수만큼 반복</td></tr>
    <tr><td style="text-align:center"><code>arr.astype(dtype)</code></td><td>배열 원소의 데이터 타입 변환</td></tr>
  </tbody>
</table>

In [36]:
# TODO 7: 2x3 행렬에 1부터 6까지 저장하고,
matrix = np.array([[1,2,3],
                  [4,5,6]])

#  - 1차원 변환
print(matrix.flatten())

#  - 전치 행렬 -> 행과 열을 바꾸기
print(matrix.T)

#  - 열 방향 2배 반복
print(np.tile(matrix, (1,2)))

#  - 1x3 크기의 1.7, 2.3, 3.9 행렬을 정수 타입 변환 행렬
arr_float = np.array([[1.7, 2.3, 3.9]])
print(arr_float.astype(int))

#    을 출력해봅시다.



[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]
[[1 2 3]]


</br>

## 배열 연산 (Vectorized Operations)
> NumPy는 <mark style="background-color:#FFF9C4; padding:2px 6px; border-radius:4px;">반복문 없이 배열 전체에 연산</mark>을 적용합니다.

In [ ]:
# TODO 8: array_a에 1x3 크기의 1, 2, 3 행렬을, array_b에 1x3 크기의 4, 5, 6 행렬을 저장하고 합, 곱, 제곱, 내적을 출력해봅시다.
array_a = np.array([[1, 2, 3]])
array_b = np.array([[4, 5, 6]])

# +
print(array_a + array_b)

# *
print(array_a * array_b)

# **
print(array_a ** 2)

# 내적하겠다~ -> array_a의 행과 array_b의 열을 곱해서 더하겠다~
print(np.dot(array_a, array_b.T))

[[5 7 9]]
[[ 4 10 18]]
[[1 4 9]]


In [42]:
# TODO 9: 1x5 크기의 3, 1, 4, 1, 5 데이터를 array에 저장하고, 최댓값, 최솟값, 최솟값 인덱스, 정렬 결과를 출력해봅시다.

array = np.array([3, 1, 4, 1, 5])

# 최댓값
print(np.max(array))

# 최솟값
print(np.min(array))

# 최솟값 인덱스
print(np.argmin(array))

# 정렬 결과
print(np.sort(array))

5
1
1
[1 1 3 4 5]


</br>

## 브로드캐스팅 (Broadcasting)
> 크기가 다른 배열 간 연산 시 <mark style="background-color:#FFF9C4; padding:2px 6px; border-radius:4px;">작은 배열을 자동으로 확장</mark>하는 규칙입니다.

In [43]:
# TODO 10: matrix에 2x3 크기의 행렬에 1부터 6까지 행렬을 저장하고, vector에 1x3 크기의 행렬에 10, 20, 30을 저장한 후 matrix + vector 브로드캐스팅 결과를 출력해봅시다.
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

vector = np.array([[10, 20, 30]])

# 브로드캐스팅이란? -> 작은 행렬이 큰 행렬에 맞춰서 자동으로 확장되는 것
print(matrix + vector)

[[11 22 33]
 [14 25 36]]


💡브로드캐스팅 규칙
> 뒤쪽 차원부터 비교하여 크기가 같거나 하나가 1이면 브로드캐스팅이 적용됩니다.

</br>

## 집계 함수 (Aggregation)

In [45]:
# TODO 11: array에 2x3 크기의 행렬에 1부터 6까지 저장하고, 전체 합, 열별 합, 행별 평균, 최댓값 인덱스를 출력해봅시다.
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

# 전체 합
print(np.sum(matrix))

# 열별 합
print(np.sum(matrix, axis=0))

# 행별 평균
print(np.mean(matrix, axis=1))

# 최댓값 인덱스
print(np.argmax(matrix))

21
[5 7 9]
[2. 5.]
5


💡axis 파라미터
> `axis=0`은 행 방향(열별 집계), `axis=1`은 열 방향(행별 집계)입니다.

</br>

## 수학 함수 및 비교 (Math Functions & Comparison)
> NumPy는 <mark style="background-color:#FFF9C4; padding:2px 6px; border-radius:4px;">원소별 수학 함수</mark>와 배열 비교 함수를 제공합니다.

<table style="width:100%">
  <thead>
    <tr>
      <th style="text-align:center">함수</th>
      <th>설명</th>
    </tr>
  </thead>
  <tbody>
    <tr><td style="text-align:center"><code>np.sin(arr)</code> / <code>np.cos(arr)</code></td><td>원소별 삼각함수 적용</td></tr>
    <tr><td style="text-align:center"><code>np.exp(arr)</code></td><td>원소별 지수함수 (e^x) 적용</td></tr>
    <tr><td style="text-align:center"><code>np.log(arr)</code></td><td>원소별 자연로그 적용</td></tr>
    <tr><td style="text-align:center"><code>np.array_equal(a, b)</code></td><td>두 배열이 완전히 같은지 비교</td></tr>
    <tr><td style="text-align:center"><code>np.allclose(a, b)</code></td><td>두 배열이 허용 오차 내에서 같은지 비교</td></tr>
  </tbody>
</table>

In [49]:
# TODO 12:
#  - 1x3 크기의 행렬에 0, π/2, π을 angles에 저장하고 sin, cos 출력
#  - 1x3 크기의 행렬에 1, 2, 3을 vals에 저장하고 지수, 로그를 출력
#  - a, b 비교, a, c 비교, 허용 오차 내 a, c 비교
#  를 출력해봅시다.

angles = np.array([[0, np.pi/2, np.pi]])

# sin 값
print(np.sin(angles))

# cos 값
print(np.cos(angles))

# vals에 1, 2, 3을 저장하고 지수, 로그를 출력
vals = np.array([[1, 2, 3]])
print(np.exp(vals))
print(np.log(vals))

# - a, b 비교, a, c 비교, 허용 오차 내 a, c 비교
a = np.array([[1, 2, 3]])
b = np.array([[1, 2, 3]])
c = np.array([[1.0, 2.0, 3.000001]])

print(np.array_equal(a, b)) # a와 b가 같은지 비교
print(np.array_equal(a, c)) # a와 c가 같은지 비교
print(np.allclose(a, c))


[[0.0000000e+00 1.0000000e+00 1.2246468e-16]]
[[ 1.000000e+00  6.123234e-17 -1.000000e+00]]
[[ 2.71828183  7.3890561  20.08553692]]
[[0.         0.69314718 1.09861229]]
True
False
True


💡array_equal vs allclose
> `np.array_equal()`은 값이 <mark style="background-color:#FFF9C4; padding:2px 6px; border-radius:4px;">정확히 일치</mark>해야 True를 반환합니다.</br>
> `np.allclose()`는 부동소수점 오차를 허용하므로 <mark style="background-color:#FFF9C4; padding:2px 6px; border-radius:4px;">수치 계산 결과 비교</mark>에 적합합니다.